import oracledb

conn = oracledb.connect(user="rm552164", password="fiap23", dsn="oracle.fiap.com.br/orcl")
cur = conn.cursor()

cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Dipirona' WHERE ID_MEDICAMENTO = 1")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Paracetamol' WHERE ID_MEDICAMENTO = 2")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Ibuprofeno' WHERE ID_MEDICAMENTO = 3")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Captopril' WHERE ID_MEDICAMENTO = 4")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Losartana' WHERE ID_MEDICAMENTO = 5")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'AAS' WHERE ID_MEDICAMENTO = 6")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Omeprazol' WHERE ID_MEDICAMENTO = 7")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Pantoprazol' WHERE ID_MEDICAMENTO = 8")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Dexametasona' WHERE ID_MEDICAMENTO = 9")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Prednisona' WHERE ID_MEDICAMENTO = 10")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Amoxicilina' WHERE ID_MEDICAMENTO = 11")
cur.execute("UPDATE T_RHSTU_MEDICAMENTO SET NM_MEDICAMENTO = 'Azitromicina' WHERE ID_MEDICAMENTO = 12")


conn.commit()
cur.close()
conn.close()